### ISSUE TITLE
SQL LITE on Project 2

### ISSUE THREAD

**Issue by cbassar0** [JaredRauch/Cyber-Dragon-Repository#5]
When I downloaded Project 2, it came up with a bug (could not find) sqlLite.c

**Comment by cbassar0** [comment]
I get an error on Qt....does it work jason?

**Comment by jweiser2** [comment]
Umm I havn't looked at it yet.. I'll be in lab 30 mins before class? My stuff was just ui files.. and thomas' s login probably didnt fundamentally impact anything..? Sorry, I'm not sure. 

Sent on a Sprint Samsung Galaxy S® III

<div>-------- Original message --------</div><div>From: cbassar0 notifications@github.com </div><div>Date:05/02/2016  9:08 AM  (GMT-08:00) </div><div>To: JaredRauch/Cyber-Dragon-Repository Cyber-Dragon-Repository@noreply.github.com </div><div>Subject: Re: [JaredRauch/Cyber-Dragon-Repository] SQL LITE on Project 2 (#5) </div><div>
</div>I get an error on Qt....does it work jason?

**Comment by tommygorney** [comment]
I also had an issue with the sqlite3 files or something, but I was able to fix it on my end, it seems the 2 files missing were in the default directory and not in the projecttwo folder

**Comment by jweiser2** [comment]
Go with my 3rd branch. It's our most up to date. Oh btw James, the error with qt was resolved by moving the db in main into the constructor for main window. I'm pretty sure jason branch 3 reflects that.

Sent on a Sprint Samsung Galaxy S® III

<div>-------- Original message --------</div><div>From: JMarcu notifications@github.com </div><div>Date:05/03/2016  4:01 PM  (GMT-08:00) </div><div>To: JaredRauch/Cyber-Dragon-Repository Cyber-Dragon-Repository@noreply.github.com </div><div>Cc: jweiser2 jweiser2@saddleback.edu, Comment comment@noreply.github.com </div><div>Subject: Re: [JaredRauch/Cyber-Dragon-Repository] SQL LITE on Project 2 (#5) </div><div>
</div>Closed #5.
