### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by JMarcu** [JaredRauch/Cyber-Dragon-Repository#8]
There are currently six branches. Can we get all stable branches merged in with main and clearly annotate what branches are currently developing what?

**Comment by cbassar0** [comment]
I think the reason for the multiple branch points is that there are two independent UIs at this point.  Also, PM stuff has not been :Foldered....We need an SQL link to the Admin UI and Customer UI...The database needs to be built. 

```
On Tuesday, May 3, 2016 4:00 PM, JMarcu <notifications@github.com> wrote:
```

 There are currently six branches, three of which are patches (which are intended to be merged immediately upon being stable). I want to work on the project but I don't even know which branch is the one that I'm supposed to be contributing to. Can we get all stable branches merged in with main and do a better job of expressing why a branch was created?—
